# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog.ui'
#
# Created: Thu Feb 18 00:31:52 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!


from PyQt4 import QtCore, QtGui
from rhelpers.widgets import LineEdit

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(900, 600)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.textEditTraffic = QtGui.QTextEdit(Dialog)
        self.textEditTraffic.setEnabled(False)
        self.textEditTraffic.setObjectName(_fromUtf8("textEditTraffic"))
        self.verticalLayout_2.addWidget(self.textEditTraffic)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEditData = LineEdit(Dialog)
        self.lineEditData.setObjectName(_fromUtf8("lineEditData"))
        self.horizontalLayout.addWidget(self.lineEditData)
        self.pushButtonSend = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSend.setFont(font)
        self.pushButtonSend.setAutoDefault(False)
        self.pushButtonSend.setObjectName(_fromUtf8("pushButtonSend"))
        self.horizontalLayout.addWidget(self.pushButtonSend)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 17, 1)
        self.labelDevice = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelDevice.setFont(font)
        self.labelDevice.setObjectName(_fromUtf8("labelDevice"))
        self.gridLayout.addWidget(self.labelDevice, 0, 1, 1, 1)
        self.lineEditDevice = QtGui.QLineEdit(Dialog)
        self.lineEditDevice.setMinimumSize(QtCore.QSize(160, 0))
        self.lineEditDevice.setMaximumSize(QtCore.QSize(160, 16777215))
        self.lineEditDevice.setObjectName(_fromUtf8("lineEditDevice"))
        self.gridLayout.addWidget(self.lineEditDevice, 1, 1, 1, 1)
        self.labelBaudRate = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelBaudRate.setFont(font)
        self.labelBaudRate.setObjectName(_fromUtf8("labelBaudRate"))
        self.gridLayout.addWidget(self.labelBaudRate, 2, 1, 1, 1)
        self.comboBoxBaudRate = QtGui.QComboBox(Dialog)
        self.comboBoxBaudRate.setObjectName(_fromUtf8("comboBoxBaudRate"))
        self.gridLayout.addWidget(self.comboBoxBaudRate, 3, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 70, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 15, 1, 1, 1)
        self.labelDataBits = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelDataBits.setFont(font)
        self.labelDataBits.setObjectName(_fromUtf8("labelDataBits"))
        self.gridLayout.addWidget(self.labelDataBits, 4, 1, 1, 1)
        self.comboBoxDataBits = QtGui.QComboBox(Dialog)
        self.comboBoxDataBits.setObjectName(_fromUtf8("comboBoxDataBits"))
        self.comboBoxDataBits.addItem(_fromUtf8(""))
        self.comboBoxDataBits.addItem(_fromUtf8(""))
        self.comboBoxDataBits.addItem(_fromUtf8(""))
        self.comboBoxDataBits.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxDataBits, 5, 1, 1, 1)
        self.labelParity = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelParity.setFont(font)
        self.labelParity.setObjectName(_fromUtf8("labelParity"))
        self.gridLayout.addWidget(self.labelParity, 6, 1, 1, 1)
        self.comboBoxParity = QtGui.QComboBox(Dialog)
        self.comboBoxParity.setObjectName(_fromUtf8("comboBoxParity"))
        self.comboBoxParity.addItem(_fromUtf8(""))
        self.comboBoxParity.addItem(_fromUtf8(""))
        self.comboBoxParity.addItem(_fromUtf8(""))
        self.comboBoxParity.addItem(_fromUtf8(""))
        self.comboBoxParity.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxParity, 7, 1, 1, 1)
        self.labelStopBits = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelStopBits.setFont(font)
        self.labelStopBits.setObjectName(_fromUtf8("labelStopBits"))
        self.gridLayout.addWidget(self.labelStopBits, 8, 1, 1, 1)
        self.comboBoxStopBits = QtGui.QComboBox(Dialog)
        self.comboBoxStopBits.setObjectName(_fromUtf8("comboBoxStopBits"))
        self.comboBoxStopBits.addItem(_fromUtf8(""))
        self.comboBoxStopBits.addItem(_fromUtf8(""))
        self.comboBoxStopBits.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxStopBits, 9, 1, 1, 1)
        self.labelFormat = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelFormat.setFont(font)
        self.labelFormat.setObjectName(_fromUtf8("labelFormat"))
        self.gridLayout.addWidget(self.labelFormat, 10, 1, 1, 1)
        self.comboBoxFormat = QtGui.QComboBox(Dialog)
        self.comboBoxFormat.setMinimumSize(QtCore.QSize(160, 0))
        self.comboBoxFormat.setMaximumSize(QtCore.QSize(160, 16777215))
        self.comboBoxFormat.setObjectName(_fromUtf8("comboBoxFormat"))
        self.comboBoxFormat.addItem(_fromUtf8(""))
        self.comboBoxFormat.addItem(_fromUtf8(""))
        self.comboBoxFormat.addItem(_fromUtf8(""))
        self.comboBoxFormat.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxFormat, 11, 1, 1, 1)
        self.checkBoxLeadingZeroes = QtGui.QCheckBox(Dialog)
        self.checkBoxLeadingZeroes.setObjectName(_fromUtf8("checkBoxLeadingZeroes"))
        self.gridLayout.addWidget(self.checkBoxLeadingZeroes, 12, 1, 1, 1)
        self.checkBoxRawText = QtGui.QCheckBox(Dialog)
        self.checkBoxRawText.setObjectName(_fromUtf8("checkBoxRawText"))
        self.gridLayout.addWidget(self.checkBoxRawText, 13, 1, 1, 1)
        self.checkBoxTimestamp = QtGui.QCheckBox(Dialog)
        self.checkBoxTimestamp.setObjectName(_fromUtf8("checkBoxTimestamp"))
        self.gridLayout.addWidget(self.checkBoxTimestamp, 14, 1, 1, 1)
        self.pushButtonOpenClose = QtGui.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOpenClose.setFont(font)
        self.pushButtonOpenClose.setAutoDefault(False)
        self.pushButtonOpenClose.setObjectName(_fromUtf8("pushButtonOpenClose"))
        self.gridLayout.addWidget(self.pushButtonOpenClose, 16, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.comboBoxFormat.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEditDevice, self.lineEditData)
        Dialog.setTabOrder(self.lineEditData, self.pushButtonSend)
        Dialog.setTabOrder(self.pushButtonSend, self.comboBoxFormat)
        Dialog.setTabOrder(self.comboBoxFormat, self.checkBoxTimestamp)
        Dialog.setTabOrder(self.checkBoxTimestamp, self.textEditTraffic)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "BSC debugger - 1.1.1", None))
        self.pushButtonSend.setText(_translate("Dialog", "Send", None))
        self.labelDevice.setText(_translate("Dialog", "Device:", None))
        self.lineEditDevice.setText(_translate("Dialog", "/dev/ttyS0", None))
        self.labelBaudRate.setText(_translate("Dialog", "Baud rate:", None))
        self.labelDataBits.setText(_translate("Dialog", "Data bits:", None))
        self.comboBoxDataBits.setItemText(0, _translate("Dialog", "5", None))
        self.comboBoxDataBits.setItemText(1, _translate("Dialog", "6", None))
        self.comboBoxDataBits.setItemText(2, _translate("Dialog", "7", None))
        self.comboBoxDataBits.setItemText(3, _translate("Dialog", "8", None))
        self.labelParity.setText(_translate("Dialog", "Parity:", None))
        self.comboBoxParity.setItemText(0, _translate("Dialog", "None", None))
        self.comboBoxParity.setItemText(1, _translate("Dialog", "Even", None))
        self.comboBoxParity.setItemText(2, _translate("Dialog", "Odd", None))
        self.comboBoxParity.setItemText(3, _translate("Dialog", "Mark", None))
        self.comboBoxParity.setItemText(4, _translate("Dialog", "Space", None))
        self.labelStopBits.setText(_translate("Dialog", "Stop bits:", None))
        self.comboBoxStopBits.setItemText(0, _translate("Dialog", "1", None))
        self.comboBoxStopBits.setItemText(1, _translate("Dialog", "1.5", None))
        self.comboBoxStopBits.setItemText(2, _translate("Dialog", "2", None))
        self.labelFormat.setText(_translate("Dialog", "Format:", None))
        self.comboBoxFormat.setItemText(0, _translate("Dialog", "Bin", None))
        self.comboBoxFormat.setItemText(1, _translate("Dialog", "Oct", None))
        self.comboBoxFormat.setItemText(2, _translate("Dialog", "Dec", None))
        self.comboBoxFormat.setItemText(3, _translate("Dialog", "Hex", None))
        self.checkBoxLeadingZeroes.setText(_translate("Dialog", "Leading zeroes", None))
        self.checkBoxRawText.setText(_translate("Dialog", "Raw text", None))
        self.checkBoxTimestamp.setText(_translate("Dialog", "Timestamp", None))
        self.pushButtonOpenClose.setText(_translate("Dialog", "Open", None))

